spring:
    h2:
        console:
            enabled: true
            path: /h2-console
    datasource:
        url: jdbc:h2:mem:empresa
        username: sa
        password:
        driver-class-name: org.h2.Driver
        generate-unique-name: false
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: create
        generate-ddl: true
        defer-datasource-initialization: true
        database-platform: org.hibernate.dialect.H2Dialect